'use client';
import Link from 'next/link';
import {useState} from 'react';
import {ArrowRight,Trash2,ShoppingBag,Copy,MessageCircle} from 'lucide-react';
import {useBag} from './bag-provider';
import {getProduct,money} from '@/data/products';
import {whatsappHref,storeConfig} from '@/lib/store-config';
import {QuantityPicker} from '@/components/catalog/quantity-picker';
import {Button} from '@/components/ui/button';
import {Empty,EmptyHeader,EmptyTitle,EmptyDescription,EmptyMedia} from '@/components/ui/empty';
import {Skeleton} from '@/components/ui/skeleton';
export function BagPage(){const bag=useBag();const [status,setStatus]=useState('');return <main id="main" className="bag-page wrap"><div className="breadcrumb"><Link href="/">Inicio</Link><span>/</span><span>Mi bolsa</span></div><div className="bag-title"><h1>Tu selección<em>.</em></h1><Link href="/catalogo" className="text-link">Seguir explorando <ArrowRight size={18}/></Link></div>{!bag.ready?<div className="bag-loading" aria-label="Cargando selección"><Skeleton className="h-48 w-full"/></div>:bag.items.length===0?<Empty className="empty-state"><EmptyHeader><EmptyMedia><ShoppingBag size={32} strokeWidth={1}/></EmptyMedia><EmptyTitle>Todo empieza con una prenda.</EmptyTitle><EmptyDescription>Tu bolsa está vacía. Explora la colección y encuentra tus esenciales.</EmptyDescription></EmptyHeader><Button asChild className="action"><Link href="/catalogo">Explorar la colección <ArrowRight/></Link></Button></Empty>:<div className="bag-layout"><section aria-label="Prendas seleccionadas">{bag.items.map(item=>{const p=getProduct(item.slug)!;return <article className="bag-item" key={item.slug+item.size}><Link href={'/producto/'+p.slug}><img src={p.images.front} alt={`${p.name} ${p.color}`} width="896" height="1200"/></Link><div className="bag-item-info"><Link href={'/producto/'+p.slug}>{p.name}</Link><p>{p.color} / Talla {item.size}</p><p>{money(p.price)} por prenda</p><QuantityPicker label={`${p.name}, talla ${item.size}`} value={item.quantity} onChange={q=>bag.change(item.slug,item.size,q)}/></div><div className="bag-item-side"><span>{money(p.price*item.quantity)}</span><Button variant="ghost" size="icon" aria-label={`Eliminar ${p.name}, talla ${item.size}`} onClick={()=>bag.remove(item.slug,item.size)}><Trash2 size={16}/></Button></div></article>})}</section><aside className="bag-summary"><h2>Casi tuyos.</h2><div className="summary-row"><span>Selección</span><span>{bag.count} {bag.count===1?'prenda':'prendas'}</span></div><div className="summary-row"><span>Envío</span><span>Por confirmar</span></div><div className="summary-row total"><span>Subtotal</span><span>{money(bag.subtotal)}</span></div><Button asChild className="action"><a href={whatsappHref(bag.message)} target="_blank" rel="noopener noreferrer"><MessageCircle size={18}/>Consultar por WhatsApp</a></Button><p>Disponibilidad y envío por confirmar. No se realiza ningún cobro ni reserva.</p>{!storeConfig.whatsappNumber&&<p>Demo: WhatsApp te permitirá elegir a quién enviar la consulta. No se envía automáticamente.</p>}<details><summary>Ver el mensaje de mi consulta</summary><pre>{bag.message}</pre><Button variant="outline" onClick={async()=>{try{await navigator.clipboard.writeText(bag.message);setStatus('Mensaje copiado.')}catch{setStatus('Puedes seleccionar y copiar el texto de arriba.')}}}><Copy size={14}/>Copiar mensaje</Button><div className="copy-status" role="status">{status}</div></details></aside></div>}</main>}
