'use client';
import Link from 'next/link';
import {usePathname,useRouter} from 'next/navigation';
import {useState} from 'react';
import {Search,ShoppingBag,ArrowRight} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {useBag} from '@/features/bag/bag-provider';
export function SiteHeader(){const {count}=useBag();const pathname=usePathname();const router=useRouter();const [open,setOpen]=useState(false);const [q,setQ]=useState('');return <><a className="skip-link" href="#main">Saltar al contenido</a><div className="announcement">LO ESENCIAL, A TU MANERA.<span>COLECCIÓN 01</span></div><header className="site-header"><div className="header-inner wrap"><Link href="/" className="wordmark" aria-label="TRAMA, inicio">TRAMA<span>®</span></Link><nav aria-label="Navegación principal"><Link href="/catalogo?coleccion=mujer">Mujer</Link><Link href="/catalogo?coleccion=hombre">Hombre</Link><Link href="/catalogo" className={pathname==='/catalogo'?'nav-active':''}>La colección</Link></nav><div className="header-actions"><Button variant="ghost" size="icon" aria-label="Buscar prendas" onClick={()=>setOpen(true)}><Search size={20}/></Button><Button asChild variant="ghost" className="bag-link"><Link href="/bolsa" aria-label={`Bolsa, ${count} prendas`}><ShoppingBag size={20}/><span className="bag-word">Bolsa</span><span className="bag-count">{count}</span></Link></Button></div></div></header><Sheet open={open} onOpenChange={setOpen}><SheetContent side="top" className="search-sheet"><SheetHeader><SheetTitle>Encuentra tu próximo esencial.</SheetTitle><SheetDescription>Busca por prenda, color o colección.</SheetDescription></SheetHeader><form className="search-form" onSubmit={e=>{e.preventDefault();router.push('/catalogo?q='+encodeURIComponent(q.trim()));setOpen(false)}}><Input aria-label="Buscar por prenda o color" placeholder="Prueba con ‘polo’ o ‘marfil’" value={q} onChange={e=>setQ(e.target.value)}/><Button type="submit" className="action">Buscar <ArrowRight size={18}/></Button></form></SheetContent></Sheet></>}
