'use client';
import {useSearchParams,useRouter} from 'next/navigation';
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {ArrowRight,Search} from 'lucide-react';
import {products} from '@/data/products';
import {ProductCard} from '@/components/catalog/product-card';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Empty,EmptyHeader,EmptyTitle,EmptyDescription} from '@/components/ui/empty';
const normalize=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
function Filter({label,value,options,onChange}:{label:string;value:string;options:{value:string;label:string}[];onChange:(v:string)=>void}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue placeholder={label}/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select>}
export function Catalog(){const params=useSearchParams();const router=useRouter();const gender=params.get('coleccion')||'todo';const query=params.get('q')||'';const category=params.get('categoria')||'todo';const size=params.get('talla')||'todo';const price=params.get('precio')||'todo';const sort=params.get('orden')||'recomendado';const [draft,setDraft]=useState(query);useEffect(()=>setDraft(query),[query]);
 const setFilter=(key:string,value:string)=>{const p=new URLSearchParams(params.toString());if(value==='todo'||!value)p.delete(key);else p.set(key,value);router.replace('/catalogo'+(p.size?'?'+p.toString():''),{scroll:false})};
 const base=products.filter(p=>gender==='todo'||!['mujer','hombre'].includes(gender)||p.gender===gender);const cats=[...new Set(base.map(p=>p.category))];const sizes=[...new Set(base.filter(p=>category==='todo'||p.category===category).flatMap(p=>p.sizes))];
 const visible=base.filter(p=>(category==='todo'||p.category===category)&&(size==='todo'||p.sizes.includes(size))&&(price==='todo'||(price==='hasta-80'?p.price<=80:p.price>80))&&normalize(p.name+' '+p.color+' '+p.category+' '+p.gender).includes(normalize(query)));
 if(sort==='menor')visible.sort((a,b)=>a.price-b.price);if(sort==='mayor')visible.sort((a,b)=>b.price-a.price);if(sort==='nombre')visible.sort((a,b)=>a.name.localeCompare(b.name));
 const dirty=!!(query||category!=='todo'||size!=='todo'||price!=='todo');const title=gender==='mujer'?'Esenciales de mujer.':gender==='hombre'?'Esenciales de hombre.':'La colección.';
 return <main id="main"><section className="page-intro wrap"><div className="breadcrumb"><Link href="/">Inicio</Link><span>/</span><span>La colección</span></div><div className="page-title-row"><h1>{title}</h1><p>Colores que se encuentran.<br/>Prendas que se quedan.</p></div><nav className="catalog-tabs" aria-label="Colecciones">{[['todo','Todo'],['mujer','Mujer'],['hombre','Hombre']].map(([g,label])=><Link key={g} className={gender===g?'active':''} href={'/catalogo'+(g==='todo'?'':'?coleccion='+g)} aria-current={gender===g?'page':undefined}>{label} <sup>{g==='todo'?'12':'6'}</sup></Link>)}</nav></section>
 <section className="wrap" aria-label="Filtros y prendas"><div className="catalog-toolbar"><div className="filter-controls"><Filter label="Categoría" value={category} onChange={v=>{const p=new URLSearchParams(params.toString());p.delete('talla');v==='todo'?p.delete('categoria'):p.set('categoria',v);router.replace('/catalogo?'+p.toString(),{scroll:false})}} options={[{value:'todo',label:'Categoría'},...cats.map(v=>({value:v,label:v}))]}/><Filter label="Talla" value={size} onChange={v=>setFilter('talla',v)} options={[{value:'todo',label:'Talla'},...sizes.map(v=>({value:v,label:v}))]}/><Filter label="Precio" value={price} onChange={v=>setFilter('precio',v)} options={[{value:'todo',label:'Precio'},{value:'hasta-80',label:'Hasta S/ 80'},{value:'mas-80',label:'Más de S/ 80'}]}/></div><form className="query-form" onSubmit={e=>{e.preventDefault();setFilter('q',draft.trim())}}><Input aria-label="Buscar en la colección" placeholder="Buscar prenda o color" value={draft} onChange={e=>setDraft(e.target.value)}/><Button type="submit" variant="ghost" size="icon" aria-label="Aplicar búsqueda"><Search size={18}/></Button></form><div className="sort-control"><Filter label="Ordenar prendas" value={sort} onChange={v=>setFilter('orden',v)} options={[{value:'recomendado',label:'Recomendado'},{value:'menor',label:'Menor precio'},{value:'mayor',label:'Mayor precio'},{value:'nombre',label:'Nombre A–Z'}]}/></div></div><div className="catalog-results"><div className="result-count"><span role="status">{visible.length} {visible.length===1?'prenda':'prendas'}{query?` para “${query}”`:''}</span>{dirty&&<Button variant="link" className="filter-reset" onClick={()=>router.replace('/catalogo'+(gender==='todo'?'':'?coleccion='+gender),{scroll:false})}>Limpiar filtros</Button>}</div>{visible.length?<div className="product-grid">{visible.map(p=><ProductCard key={p.slug} product={p}/>)}</div>:<Empty className="empty-state"><EmptyHeader><EmptyTitle>No encontramos esa combinación.</EmptyTitle><EmptyDescription>Prueba otra talla, color o categoría.</EmptyDescription></EmptyHeader><Button asChild className="action"><Link href="/catalogo">Ver todas las prendas <ArrowRight/></Link></Button></Empty>}</div></section></main>
}
