'use client';
import {useEffect,useRef} from 'react';
import {products} from '@/data/products';
import {useBag} from '@/features/bag/bag-provider';
type Tool={name:string;description:string;inputSchema:object;annotations:{readOnlyHint:boolean};execute:(input:unknown)=>unknown};
type ModelContext={registerTool:(tool:Tool,options:{signal:AbortSignal})=>void|Promise<void>};
export function CatalogTools(){const bag=useBag();const current=useRef(bag);useEffect(()=>{current.current=bag},[bag]);useEffect(()=>{const context=(document as Document&{modelContext?:ModelContext}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();
 const tools:Tool[]=[{name:'search_trama_catalog',description:'Read the demo catalog, optionally filtering by collection and text. Does not change the page or the bag.',inputSchema:{type:'object',properties:{collection:{type:'string',enum:['mujer','hombre','todo']},query:{type:'string'}},additionalProperties:false},annotations:{readOnlyHint:true},execute(input){if(!input||typeof input!=='object'||Array.isArray(input))throw new Error('Expected an object');const data=input as Record<string,unknown>;if(Object.keys(data).some(k=>!['collection','query'].includes(k))||(data.collection!==undefined&&!['mujer','hombre','todo'].includes(String(data.collection)))||(data.query!==undefined&&typeof data.query!=='string'))throw new Error('Invalid catalog filter');const q=String(data.query||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();return products.filter(p=>(!data.collection||data.collection==='todo'||p.gender===data.collection)&&(p.name+' '+p.color).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().includes(q)).map(p=>({slug:p.slug,name:p.name,color:p.color,price:p.price,currency:'PEN',sizes:p.sizes,url:'/producto/'+p.slug}))}},
 {name:'read_trama_selection',description:'Read the current browser-local clothing selection and its reference subtotal. No purchase is made and no message is sent.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(input){if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw new Error('Expected an empty object');return {ready:current.current.ready,items:current.current.items,subtotal:current.current.subtotal,currency:'PEN'}}}];
 for(const tool of tools)try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{})}catch{}return ()=>lifecycle.abort();},[]);return null}
