"use client";
import Link from "next/link";
import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { imageLibrary } from "@/data/image-library";
import { productInput, type ProductInput } from "../products/validation";
import { saveProduct } from "../products/actions";
const empty = (categoryId: string): ProductInput => ({ name: "", slug: "", description: "", categoryId, collection: "mujer", fit: "Regular", price: "", status: "draft", position: 100, featuredPosition: null, colors: [{ code: "color-1", name: "", hex: "#222222" }], variants: [{ colorCode: "color-1", sizeCode: "", sku: "", stock: null }], images: [] });
export function ProductForm({ initial, categories }: { initial?: ProductInput; categories: { id: string; name: string }[] }) {
  const [value, setValue] = useState(initial ?? empty(categories[0]?.id ?? "")); const [errors, setErrors] = useState<string[]>([]); const [pending, start] = useTransition(); const router = useRouter();
  function field<K extends keyof ProductInput>(key: K, entry: ProductInput[K]) { setValue((old) => ({ ...old, [key]: entry })); }
  function movePhoto(index: number, by: number) { const images = [...value.images]; const next = index + by; if (next < 0 || next >= images.length) return; [images[index], images[next]] = [images[next], images[index]]; field("images", images); }
  function save(status: ProductInput["status"]) {
    const input = { ...value, status }; const parsed = productInput.safeParse(input);
    if (!parsed.success) { setErrors(parsed.error.issues.map((i) => i.path.join(".") + ": " + i.message)); return; }
    start(async () => { setErrors([]); const result = await saveProduct(parsed.data); if (!result.ok) { setErrors([result.error]); return; } router.push("/admin/products/" + result.id); router.refresh(); });
  }
  return <><div className="admin-title"><div><p className="eyebrow">{value.id ? "EDITAR PRENDA" : "NUEVA PRENDA"}</p><h1>{value.name || "Una nueva idea"}<em>.</em></h1></div><Link href="/admin">← Volver al listado</Link></div>
    <form className="admin-form" onSubmit={(e) => { e.preventDefault(); save("draft"); }}>
    <fieldset disabled={pending}><legend>01 / La prenda</legend><div className="admin-grid"><label>Nombre<input required maxLength={160} value={value.name} onChange={(e) => field("name", e.target.value)} /></label><label>Slug / URL<input required pattern="[a-z0-9]+(-[a-z0-9]+)*" readOnly={Boolean(value.id)} value={value.slug} onChange={(e) => field("slug", e.target.value)} /><small>Se conserva después de crear para mantener los enlaces.</small></label><label>Categoría<select value={value.categoryId} onChange={(e) => field("categoryId", e.target.value)}>{categories.map((c) => <option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label>Colección<select value={value.collection} onChange={(e) => field("collection", e.target.value as ProductInput["collection"])}><option value="mujer">Mujer</option><option value="hombre">Hombre</option></select></label><label>Precio PEN<input inputMode="decimal" placeholder="49.90" value={value.price} onChange={(e) => field("price", e.target.value)} /></label><label>Corte<input value={value.fit} onChange={(e) => field("fit", e.target.value)} /></label><label>Orden en catálogo<input type="number" min="0" max="100000" value={value.position} onChange={(e) => field("position", Number(e.target.value))} /></label><label>Orden destacado (opcional)<input type="number" min="0" max="1000" value={value.featuredPosition ?? ""} onChange={(e) => field("featuredPosition", e.target.value === "" ? null : Number(e.target.value))} /></label></div><label>Descripción<textarea rows={4} value={value.description} onChange={(e) => field("description", e.target.value)} /></label></fieldset>
    <fieldset disabled={pending}><legend>02 / Colores</legend>{value.colors.map((color, index) => <div className="admin-color-row" key={index}><label>Nombre<input value={color.name} onChange={(e) => field("colors", value.colors.map((c, i) => i === index ? { ...c, name: e.target.value } : c))} /></label><label>Código<input value={color.code} onChange={(e) => { const code = e.target.value; setValue((old) => ({ ...old, colors: old.colors.map((c, i) => i === index ? { ...c, code } : c), variants: old.variants.map((v) => v.colorCode === color.code ? { ...v, colorCode: code } : v), images: old.images.map((i) => i.colorCode === color.code ? { ...i, colorCode: code } : i) })); }} /></label><label>Tono<input type="color" value={color.hex} onChange={(e) => field("colors", value.colors.map((c, i) => i === index ? { ...c, hex: e.target.value } : c))} /></label><Button type="button" variant="ghost" disabled={value.colors.length === 1 || value.variants.some((v) => v.colorCode === color.code) || value.images.some((i) => i.colorCode === color.code)} onClick={() => field("colors", value.colors.filter((_, i) => i !== index))}>Quitar</Button></div>)}<Button type="button" variant="outline" onClick={() => field("colors", [...value.colors, { code: "color-" + (value.colors.length + 1), name: "", hex: "#222222" }])}>Añadir color</Button></fieldset>
    <fieldset disabled={pending}><legend>03 / Tallas y variantes</legend><p>Stock vacío significa «por confirmar». Para publicar variantes nuevas indica una cantidad, incluido cero si está agotada. No uses cantidades ficticias en las prendas importadas.</p>{value.variants.map((variant, index) => <div className="admin-variant-row" key={variant.id ?? index}><label>Color<select value={variant.colorCode} onChange={(e) => field("variants", value.variants.map((v, i) => i === index ? { ...v, colorCode: e.target.value } : v))}>{value.colors.map((c, i) => <option key={i} value={c.code}>{c.name || c.code}</option>)}</select></label><label>Talla<input value={variant.sizeCode} onChange={(e) => field("variants", value.variants.map((v, i) => i === index ? { ...v, sizeCode: e.target.value } : v))} /></label><label>SKU<input value={variant.sku} onChange={(e) => field("variants", value.variants.map((v, i) => i === index ? { ...v, sku: e.target.value } : v))} /></label><label>Stock<input type="number" min="0" step="1" placeholder="Por confirmar" value={variant.stock ?? ""} onChange={(e) => field("variants", value.variants.map((v, i) => i === index ? { ...v, stock: e.target.value === "" ? null : Number(e.target.value) } : v))} /></label><Button type="button" variant="ghost" disabled={value.variants.length === 1} onClick={() => field("variants", value.variants.filter((_, i) => i !== index))}>Quitar</Button></div>)}<Button type="button" variant="outline" onClick={() => field("variants", [...value.variants, { colorCode: value.colors[0]?.code ?? "", sizeCode: "", sku: "", stock: null }])}>Añadir variante</Button></fieldset>
    <fieldset disabled={pending}><legend>04 / Portada y galería</legend><p>La primera foto es la portada. Selecciona imágenes existentes; no se suben archivos.</p><div className="admin-selected-images">{value.images.map((image, index) => <article key={image.url}><img src={image.url} alt={image.alt} width="120" height="160" /><strong>{index === 0 ? "Portada" : "Foto " + (index + 1)}</strong><label>Texto alternativo<input value={image.alt} onChange={(e) => field("images", value.images.map((v, i) => i === index ? { ...v, alt: e.target.value } : v))} /></label><label>Color<select value={image.colorCode ?? ""} onChange={(e) => field("images", value.images.map((v, i) => i === index ? { ...v, colorCode: e.target.value || null } : v))}><option value="">Todos</option>{value.colors.map((c, i) => <option key={i} value={c.code}>{c.name || c.code}</option>)}</select></label><div><Button type="button" variant="ghost" disabled={index === 0} aria-label={"Subir foto " + (index + 1)} onClick={() => movePhoto(index, -1)}>↑</Button><Button type="button" variant="ghost" disabled={index === value.images.length - 1} aria-label={"Bajar foto " + (index + 1)} onClick={() => movePhoto(index, 1)}>↓</Button><Button type="button" variant="ghost" onClick={() => field("images", value.images.filter((_, i) => i !== index))}>Quitar</Button></div></article>)}</div><details className="admin-library"><summary>Explorar biblioteca de TRAMA ({imageLibrary.length} fotos)</summary><div className="admin-library-grid">{imageLibrary.map((image) => <button type="button" key={image.url} disabled={value.images.some((i) => i.url === image.url)} onClick={() => field("images", [...value.images, { url: image.url, alt: image.label, colorCode: null }])}><img src={image.url} alt={image.label} loading="lazy" width="120" height="160" /><span>{image.label}</span><strong>{value.images.some((i) => i.url === image.url) ? "Seleccionada" : "Seleccionar +"}</strong></button>)}</div></details></fieldset>
    {!!errors.length && <div role="alert" className="admin-error"><strong>Revisa los siguientes datos:</strong><ul>{errors.map((error, i) => <li key={i}>{error}</li>)}</ul></div>}<div className="admin-save"><Button disabled={pending} type="submit" variant="outline">{pending ? "Guardando…" : "Guardar borrador"}</Button><Button disabled={pending} type="button" className="action" onClick={() => save("published")}>Guardar y publicar</Button>{value.id && <><Button disabled={pending} type="button" variant="ghost" onClick={() => save("archived")}>Guardar y archivar</Button><Link href={"/admin/products/" + value.id + "/preview"}>Previsualizar cambios guardados ↗</Link></>}</div></form>
  </>;
}
